 # Naive Bayes : Classify review of customers

In [44]:
import numpy as np
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/charankamarapu/ML-Naive-Bayes-Algorithm-and-Models/main/BernoulliNB_review_classsification/Restaurant_Reviews.tsv',sep="\t")
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [45]:
df.shape

(1000, 2)

In [46]:
df['Liked'].value_counts()

1    500
0    500
Name: Liked, dtype: int64

# Text Cleaning -
### Remove Punctuation, remove stop words, tokenize the setence into words, convert words into numbers

In [47]:
from nltk.corpus import stopwords

stopWords = set(stopwords.words('english'))
print(stopWords)


{'too', 'having', 'was', 'doing', "didn't", 'or', 'from', "haven't", 'where', 'as', 'between', 'll', 'hadn', 'yours', 'under', "you're", 'am', 'were', 'whom', 'after', 'here', 'herself', 'she', 'who', 'ours', 'what', 'own', 'there', 'mustn', 'out', 'been', 'yourself', 'just', 'of', 'some', 're', "couldn't", 'so', 'other', 'through', 'y', "shouldn't", 'into', 'that', 'have', "you'll", 'these', 'not', 'he', 'is', 'did', 'same', 'off', 'with', "she's", 'no', "should've", 'if', 'nor', "that'll", 'd', 'mightn', 'against', 'now', 'isn', "mightn't", 'very', "wasn't", 'because', 'we', 'won', 'the', 'yourselves', 'ourselves', 'its', 'but', 'o', "won't", 'it', 'during', 'most', 'them', 'ma', 'up', 'to', 'being', 'wasn', 'his', "mustn't", "don't", "isn't", 'me', 'each', 'don', 'by', 'her', 'they', 'more', 'this', 'itself', 'm', 'further', 'him', 'until', "aren't", 's', "needn't", 've', 'are', 'and', 'few', 'over', 'again', "you've", "you'd", 'hasn', "hasn't", 'how', 'their', 'a', 'you', 'had', 'a

In [48]:
import string
def text_cleaning(a):
 cleaning = [char for char in a if char not in string.punctuation]
 #print(cleaning)
 cleaning=''.join(cleaning)
 #print(cleaning)   
 return [word for word in cleaning.split() if word.lower() not in stopwords.words('english')]



In [49]:

from sklearn.feature_extraction.text import CountVectorizer
bow_transformer = CountVectorizer(analyzer=text_cleaning).fit(df['Review']) 
  

In [50]:
title_bow = bow_transformer.transform(df['Review'])

print(title_bow)

  (0, 248)	1
  (0, 442)	1
  (0, 1540)	1
  (1, 112)	1
  (1, 1079)	1
  (2, 1408)	1
  (2, 1932)	1
  (2, 1945)	1
  (3, 265)	1
  (3, 342)	1
  (3, 380)	1
  (3, 381)	1
  (3, 541)	1
  (3, 1162)	1
  (3, 1255)	1
  (3, 1305)	1
  (3, 1651)	1
  (4, 1089)	1
  (4, 1359)	1
  (4, 1584)	1
  (4, 1755)	1
  (5, 480)	1
  (5, 792)	1
  (5, 1061)	1
  (5, 1528)	1
  :	:
  (997, 1072)	1
  (997, 1199)	1
  (997, 2135)	1
  (998, 288)	1
  (998, 387)	1
  (998, 953)	1
  (998, 1072)	1
  (998, 1420)	1
  (998, 1955)	1
  (998, 1966)	1
  (998, 2020)	1
  (998, 2099)	1
  (998, 2106)	1
  (999, 618)	1
  (999, 679)	1
  (999, 879)	1
  (999, 925)	1
  (999, 1113)	1
  (999, 1274)	1
  (999, 1572)	1
  (999, 1721)	1
  (999, 1966)	1
  (999, 1979)	1
  (999, 2083)	1
  (999, 2138)	1


In [51]:
tokens = bow_transformer.get_feature_names()

In [52]:
X = title_bow.toarray()
print(X)

 
X.shape  # 1000,2159  # 2159 seperate words in our dataset and 1000 rows

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(1000, 2159)

In [53]:
# If you want you can store it in a dataframe also
dd=pd.DataFrame(data=title_bow.toarray(),columns=tokens)
dd

1  10  100  1199  12  15  15lb  17  1979  2  ...  yellowtail  yet  youd  \
0    0   0    0     0   0   0     0   0     0  0  ...           0    0     0   
1    0   0    0     0   0   0     0   0     0  0  ...           0    0     0   
2    0   0    0     0   0   0     0   0     0  0  ...           0    0     0   
3    0   0    0     0   0   0     0   0     0  0  ...           0    0     0   
4    0   0    0     0   0   0     0   0     0  0  ...           0    0     0   
..  ..  ..  ...   ...  ..  ..   ...  ..   ... ..  ...         ...  ...   ...   
995  0   0    0     0   0   0     0   0     0  0  ...           0    0     0   
996  0   0    0     0   0   0     0   0     0  0  ...           0    0     0   
997  0   0    0     0   0   0     0   0     0  0  ...           0    0     0   
998  0   0    0     0   0   0     0   0     0  0  ...           0    0     0   
999  0   0    0     0   0   0     0   0     0  0  ...           0    0     0   

     youll  youre  yucky  yukon  yum  yummy  zero  
0        0      0      0      0    0      0     0  
1        0      0      0      0    0      0     0  
2        0      0      0      0    0      0     0  
3        0      0      0      0    0      0     0  
4        0      0      0      0    0      0     0  
..     ...    ...    ...    ...  ...    ...   ...  
995      0      0      0      0    0      0     0  
996      0      0      0      0    0      0     0  
997      0      0      0      0    0      0     0  
998      0      0      0      0    0      0     0  
999      0      0      0      0    0      0     0  

[1000 rows x 2159 columns]

In [54]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, df.Liked,test_size=0.2, random_state=50)

In [55]:
#from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB().fit(x_train,y_train)

In [56]:
prediction = model.predict(x_test)
print(prediction)

[0 1 1 0 0 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 1 0 0 1 0
 1 0 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0 1
 0 1 0 0 1 1 1 1 1 1 0 1 1 0 1 1 0 1 0 1 1 1 0 0 0 1 1 1 0 1 1 0 1 0 1 0 1
 0 1 0 0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 0 1 0 1
 0 1 1 1 0 1 1 1 0 1 1 1 0 1 0 0 0 1 1 0 1 1 1 1 1 1 0 1 0 0 1 1 0 0 0 1 0
 1 1 1 0 0 1 1 1 0 0 1 0 1 1 1]


In [57]:
from sklearn.metrics import accuracy_score

accuracy_score(prediction,y_test)

0.715

In [58]:
y_test  #actual records of y_test

316    0
459    1
854    0
11     0
978    0
      ..
37     0
981    0
38     1
333    0
157    1
Name: Liked, Length: 200, dtype: int64